# Generated by Django 5.0.6 on 2024-06-25 21:52

import publico.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publico', '0002_cliente_foto_perfil_cliente_rg_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=publico.models.GeneroCliente.choices, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
