# Generated by Django 5.0.6 on 2024-06-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interno', '0003_estado_sigla_alter_estado_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='sigla',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
