# Generated by Django 5.0.6 on 2024-06-20 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interno', '0006_alter_categoria_nome_alter_produto_nome_cidades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cidades',
            new_name='Cidade',
        ),
    ]
