print("Olá Mundo!!")
print("Outra mensagem")
print("Soma: ", 2 + 2)
print("Subtração: ", 2 - 2)
print("Multiplicação: ", 2 * 2)
print("Divisão: ", 2 / 2)
print("Resto da divisão: ", 2 % 2)

print("    *")
print("   ***")
print("  *****")
print(" *******")
print("*********")
print("   ***")
print("   ***")